### PR TITLE
Fixes for last core build

### PR DESCRIPTION
**Pull request by nycenom**
Start with no errors

### CODE REVIEW

**Comment by frozenblit** [comment]
The changes look good, thanks! Just one question: you removed the tasteId skill and some herbal function from scissors, was that intended?

**Comment by nycenom** [comment]
Hey frozen:
1. tasteId skill removal was a mistake, just added it again https://github.com/polserver/poldistro/pull/1/files
2. About herbal function, i can't find the package botanic in the files(include ":botanic:botanic), so i had to remove the function.

Feel free to merge only the changes you agree, i just started with POL!

Need to fix 2 more warnings, but not sure about the right aproach to do it:

```
Warning! objtype 0xFF01 : ObjtypeName 'SecureTradeContainer' is the same as objtype 0X1FF01
Warning! objtype 0xFF02 : ObjtypeName 'WornItemsContainer' is the same as objtype 0X1FF02
```

```
pkg\items\containers\config\itemdesc.cfg
Line 1842: Name SecureTradeContainer

config\itemdesc.cfg
Line 344: Name SecureTradeContainer
```

Rename one of those? Change type to match?

Thanks.

**Comment by nycenom** [comment]
no errors in ecompile.log

Compiled 1218 scripts in 78842 ms.

3 warnings on pol startup:

Warning! objtype 0xFF01 : ObjtypeName 'SecureTradeContainer' is the same as objtype 0X1FF01
Warning! objtype 0xFF02 : ObjtypeName 'WornItemsContainer' is the same as objtype 0X1FF02
Warning! pkg/items/clothing/cloth/onDestroy.ecl does not exist!

I will try to solve those.

**Comment by nycenom** [comment]
Not sure about the right aproach to fix the ObjtypeName warning:

pkg\items\containers\config\itemdesc.cfg
Line 1842: 	Name		SecureTradeContainer

config\itemdesc.cfg
Line 344:     Name        SecureTradeContainer

Rename one of those? Change type to match?

Thanks.

**Comment by frozenblit** [comment]
You have duplicate itemdescs, so one should be removed. Is there any difference between them, besides the location and objtype? (I think the config is set to use the 0x1FF01 and 0x1FF02 objtypes)

**Comment by nycenom** [comment]
Yeah, they are about the same. The only dif i can see is MaxItems and Maxweight of 0x1FF01 and the the file inside pkg have 'Desc'. I should use 'Max' from pkg... or config...? 

What file should hold the data, the one inside pkg or the one inside config?

config\itemdesc.cfg

```
Container 0x1FF01
{
    Name        SecureTradeContainer
    ...
    MaxItems    65535
    Maxweight   65535
}

Container 0x1FF02
{
    Name        WornItemsContainer
    ...
}
```

pkg\items\containers\config\itemdesc.cfg

```
Container 0x1FF01
{
    Name        SecureTradeContainer
    Desc        secure trade container
    ...
    Weight      0
    MaxItems        100
    MaxWeight       0
}

Container 0x1FF02
{
    Name        WornItemsContainer
    Desc        WornItemsContainer
    Graphic     0x1E5E
    ...
    Weight      0
    MaxItems    65535
    MaxWeight   65535
}
```

**Comment by frozenblit** [comment]
Remove those from config and just use the ones in the pkg. I guess someone didn't realize they were already defined... ;)

**Comment by nycenom** [comment]
nice! seems to be all right now :+1: 

https://github.com/nycenom/logsssss

check if theres anything else that need to be changed, please.

**Comment by frozenblit** [comment]
Just one more thing: I'm not sure if configs accept C-style comments, so POL may be silently doing something weird with the redefined items. Anyway, it would look cleaner without that comment in the itemdesc. :)

**Comment by nycenom** [comment]
You are more than right, configs doesn't accept it. 

That was changed already when i generated logs from last message. I did a commit to local, but forgot to sync.

**Comment by frozenblit** [comment]
Perfect, thanks! I'll merge it now. ;)

(Brasileiro?)

**Comment by nycenom** [comment]
(yes :+1: )

**Pull request merged**
